#!/usr/bin/env bash
#
# One-command setup for the optional multiplayer backend.
# See docs/SUPABASE.md for the full walkthrough.
#
# Usage:
#   ./scripts/setup-supabase.sh <project-ref> [publishable-key]
#
# - <project-ref>     : the "<ref>" in https://<ref>.supabase.co
# - [publishable-key] : sb_publishable_... (or legacy anon key). Prompted if omitted.
#
# Idempotent: safe to re-run. Requires the Supabase CLI and a prior `supabase login`.

set -euo pipefail

cd "$(dirname "$0")/.."

REF="${1:-}"
KEY="${2:-}"

err() { printf '\033[31mError: %s\033[0m\n' "$1" >&2; }
ok()  { printf '\033[32mOK: %s\033[0m\n' "$1"; }
step(){ printf '\n\033[1m==> %s\033[0m\n' "$1"; }

# 1. CLI present?
if ! command -v supabase >/dev/null 2>&1; then
  err "Supabase CLI not found."
  echo "  Install it:  brew install supabase/tap/supabase   (or: npm i -g supabase)"
  exit 1
fi
ok "Supabase CLI: $(supabase --version 2>/dev/null | head -1)"

# 2. Logged in?
if ! supabase projects list >/dev/null 2>&1; then
  err "Not logged in to the Supabase CLI."
  echo "  Run:  supabase login   (opens a browser), then re-run this script."
  exit 1
fi
ok "Logged in to Supabase"

# 3. Project ref
if [ -z "$REF" ]; then
  read -r -p "Supabase project ref (the <ref> in https://<ref>.supabase.co): " REF
fi
[ -n "$REF" ] || { err "Project ref is required."; exit 1; }

# 4. Publishable key
if [ -z "$KEY" ]; then
  read -r -p "Publishable key (sb_publishable_... or legacy anon eyJ...): " KEY
fi
[ -n "$KEY" ] || { err "Publishable key is required."; exit 1; }

URL="https://${REF}.supabase.co"

step "Linking project $REF"
supabase link --project-ref "$REF"
ok "Linked"

step "Applying database schema (supabase db push)"
supabase db push
ok "Schema applied"

step "Bundling the shared engine for the Edge Function (npm run build:edge)"
npm run build:edge
ok "Engine bundled"

step "Deploying the 'game' Edge Function"
supabase functions deploy game
ok "Function deployed"

step "Writing .env.local"
cat > .env.local <<EOF
# Supabase — client-safe values (publishable key is public, guarded by RLS).
# Generated by scripts/setup-supabase.sh. Gitignored.
VITE_SUPABASE_URL=${URL}
VITE_SUPABASE_KEY=${KEY}
EOF
ok ".env.local written"

printf '\n\033[32mMultiplayer backend ready.\033[0m  Run: npm run dev\n'
echo "   The home screen will show Create Online Game / Join with Code."
